### ISSUE TITLE
Draggable legend with touchscreen

### ISSUE THREAD

**Issue by orgalinq** [highslide-software/draggable-legend#4]
Is it possible to drag the (draggable) legend on a touchscreen? f.i. on a Ipad or Iphone?
I can't find information about this.

Kind regards,
Jan Walhof

**Comment by highslide-software** [comment]
Thanks for your request, it has been implemented now. 

Closed by dd8bd4aa80a0bc362b15f9af97afd10e45d82896

**Comment by orgalinq** [comment]
Hello Torstein,

Thank you for your work, the legend is draggable now on a touchscreen.
Additional, is it possible to block the scrolling of the screen only and when the dragging of the legend is busy? That would would make the dragging of the legend much easier to handle.

Kind regards,
Jan Walhof
