### ISSUE TITLE
Stop scrolling when dragging on touchscreen

### ISSUE THREAD

**Issue by orgalinq** [highslide-software/draggable-legend#5]
Hello Torstein,

Thank you for your work, the legend is draggable now on a touchscreen.
Is it, additional, possible to block the scrolling of the screen only and when the dragging of the legend is busy? That would would make the dragging of the legend much easier to handle.

Kind regards,
Jan Walhof

**Comment by orgalinq** [comment]
Torstein,

Thank you for the quick reply and of course for the solution.
A "world of difference" by a tiny edit.
I understand, I need more practice in js.
Thank you!

Kind regards,
Jan Walhof

2015-11-06 9:35 GMT+01:00 Torstein Hønsi <notifications@github.com>:

**Comment by highslide-software** [comment]
You're welcome Jan!
